### ISSUE TITLE
데이터 신청 답변 관련 문의

### ISSUE THREAD

**Issue by Moon-sung-woo** [emotiontts/emotiontts_open_db#3]
안녕하세요.

약 3주전 네이버 폼을 통해 데이터를 신청했습니다.

3주가 지났는데도 답변을 받지 못해 문의를 남깁니다.

답변이 없다면 데이터를 제공 받지 못하는 것일까요?

**Comment by soobo-seo** [comment]
안녕하세요. 해당 데이터를 신청해 주셔서 감사합니다.
금주 내로 제공해 드릴 예정입니다.
참고로, SpeechCorpus는 월단위로 신청을 일괄 취합해서, 월말에 제공해 드리고 있습니다.

**Comment by soobo-seo** [comment]
> 안녕하세요.
> 
> 약 3주전 네이버 폼을 통해 데이터를 신청했습니다.
> 
> 3주가 지났는데도 답변을 받지 못해 문의를 남깁니다.
> 
> 답변이 없다면 데이터를 제공 받지 못하는 것일까요?

@Moon-sung-woo 
안녕하세요. 해당 데이터를 신청해 주셔서 감사합니다.
금주 내로 제공해 드릴 예정입니다.
참고로, SpeechCorpus는 월단위로 신청을 일괄 취합해서, 월말에 제공해 드리고 있습니다.

**Comment by Moon-sung-woo** [comment]
> > 안녕하세요.
> > 약 3주전 네이버 폼을 통해 데이터를 신청했습니다.
> > 3주가 지났는데도 답변을 받지 못해 문의를 남깁니다.
> > 답변이 없다면 데이터를 제공 받지 못하는 것일까요?
> 
> @Moon-sung-woo
> 안녕하세요. 해당 데이터를 신청해 주셔서 감사합니다.
> 금주 내로 제공해 드릴 예정입니다.
> 참고로, SpeechCorpus는 월단위로 신청을 일괄 취합해서, 월말에 제공해 드리고 있습니다.

답변 주셔서 감사합니다. 월단위로 신청을 일괄 취합하는지 몰랐습니다 ㅠㅠ

데이터 감사합니다~!

**Comment by dori2063** [comment]
안녕하세요. 데이터셋 풀 버전을 받아보고 싶은데요. 
이슈를 보니 신청을 네이버 폼으로 하면 되는 것 같습니다.
네이버 폼을 어디서 찾아볼 수 있을까요?

**Comment by soobo-seo** [comment]
> 안녕하세요. 데이터셋 풀 버전을 받아보고 싶은데요.
> 이슈를 보니 신청을 네이버 폼으로 하면 되는 것 같습니다.
> 네이버 폼을 어디서 찾아볼 수 있을까요?

http://naver.me/GaQSRZdm 로 신청해 주세요
