### ISSUE TITLE
준수사항 2번과 4번 질문드립니다.

### ISSUE THREAD

**Issue by hash2430** [emotiontts/emotiontts_open_db#4]
안녕하세요. 
요청 양식에 대한 응답을 주셔서 감사합니다.
응답 메일에 나와 있는 준수 사항 2번과 4번에 대해 여쭤볼 것이 있습니다.
승인을 얻은 '연구자'만 열람할 수 있다는 것은,
같은 소속이더라도 한 팀에서 2명 이상의 연구자가 해당 DB에 액세스하고 싶다면 각각 양식을 제출해야 하는것인가요? 팀에서 한명이 양식을 제출하고 2명이 액세스하면 안되는 것인지 궁금합니다.
또한 4번에 결과물에 대한 해당 정보를 제공하는 것이 정확히 어떤 의미인지 궁금합니다.

**Comment by soobo-seo** [comment]
- 원칙적으로 승인을 얻은 연구자만 열람 가능합니다. 
- 제공받은 DB에 기반하여  기술연구한 논문이나 결과물(예, 특허 등)이 있다면, 리포트해 주셔야 합니다.
