### ISSUE TITLE
잘못된 음성 파일이 있는 거 같습니다.

### ISSUE THREAD

**Issue by junkeon0412** [emotiontts/emotiontts_open_db#5]
우선 이렇게 고퀄리티의 데이터를 공개해주셔서 감사합니다
덕분에 한국어 데이터로 좋은 연구를 진행할 수 있어서 감사 인사를 드립니다

데이터 사용에 앞서 전체 데이터에 대해 기본적인 검수를 진행하였는데, 잘못된 음성 파일이 몇개 있는 거 같아서 공유드리고자 합니다

모든 데이터를 음성 인식기로 돌리고 스크립트와 비교하여 간단하게 검수를 진행하였는데, 다음의 여섯개의 파일이 잘못된 거 같습니다

실제로도 들어보면 잡음만 녹음된 음성이 들립니다

확인 부탁드립니다

![image](https://user-images.githubusercontent.com/35945268/114483371-2f957d00-9c43-11eb-9534-3b243185f726.png)

**Comment by soobo-seo** [comment]
검토 감사합니다. ^^
이메일 주소를 알려주시면 해당 파일을 전달해 드리겠습니다.

**Comment by junkeon0412** [comment]
junkeon_park@tmax.co.kr로 부탁드립니다 ㅎㅎ
